apiVersion: v1
kind: ServiceAccount
metadata:
  name: illumidesk-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grader-setup-service
  labels:
    app: illumidesk
    component: grader-setup-service
rules:
  - apiGroups:
     - ""
     - extensions
    resources:
     - services
     - pods/status
    verbs:
     - create
     - get
     - list
     - update
     - watch
     - patcn
     - delete
  - apiGroups:
      - "apps"
      - extensions
    resources:
      - pods
      - secrets
      - services
      - namespaces
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grader-setup-service
  labels:
    app: illumidesk
    component: grader-setup-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grader-setup-service
subjects:
  - kind: ServiceAccount
    name: illumidesk-account
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: grader-setup-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    component: grader-setup-service
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grader-setup-service
  labels:
    app: illumidesk
    component: grader-setup-service
spec:
  selector:
    matchLabels:
      component: grader-setup-service
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: illumidesk
        component: grader-setup-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: grader-setup-container
          image: netoisc/grader-setup-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: GRADER_IMAGE_NAME
              value: 'illumidesk/grader-notebook:latest'
      serviceAccountName: illumidesk-account
