apiVersion: v1
kind: ServiceAccount
metadata:
  name: illumidesk-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gradersetup
  name: gradersetup
rules:
  - apiGroups:
     - ""
     - extensions
    resources:
     - configmaps
     - endpoints
     - ingresses
     - ingresses/status
     - services
     - pods/status
    verbs:
     - create
     - get
     - list
     - update
     - watch
     - patcn
  - apiGroups:
      - "apps"
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: gradersetup
  name: gradersetup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gradersetup
subjects:
  - kind: ServiceAccount
    name: illumidesk-account
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: gradersetup
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: gradersetup
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradersetup
  labels:
    app: gradersetup
spec:
  selector:
    matchLabels:
      app: gradersetup
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gradersetup
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: gradersetup-container
          image: netoisc/grader-setup-app
          ports:
            - containerPort: 8000
      serviceAccountName: illumidesk-account
